import {
  Atom,
  Layers,
  Braces,
  Boxes,
  Code2,
  Palette,
  Server,
  Zap,
  Database,
  ShoppingBag,
  GitBranch,
  MonitorSmartphone,
  Terminal,
} from 'lucide-react';

export const techIcon = {
  'React.js': Atom,
  'Next.js': Layers,
  JavaScript: Braces,
  'Redux Toolkit': Boxes,
  HTML5: Code2,
  CSS3: Palette,
  'Node.js': Server,
  Express: Zap,
  MySQL: Database,
  'Shopify Node App': ShoppingBag,
  'Git / GitHub': GitBranch,
  Windows: MonitorSmartphone,
  Ubuntu: Terminal,
};
